config/routes.rb
Rails.application.routes.draw do
  root to: 'groups#home'

  resources :users do
    collection do
      post :confirm
      get :pass_edit
      get :destroy_confirm
    end
  end

  resources :sessions,only:[:new,:create,:destroy]

  resources :groups do
    collection do
      post :confirm
      get :manager_edit
    end
  end

  resources :joins,only:[:create,:destroy]

  resources :boards

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  mount_uploader :image, BoardImageUploader
  belongs_to :user
  belongs_to :group

  validates :content ,presence:true ,length: { maximum: 440 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :joins, dependent: :destroy
  has_many :join_users,through: :joins,source: :user
  has_many :boards, dependent: :destroy
  has_many :board_users,through: :joins,source: :user


  validates :name ,presence:true
  validates :place ,presence:true ,length: { maximum: 30 }
  validates :time ,presence:true ,length: { maximum: 30 }
  validates :content ,presence:true ,length: { maximum: 500 }
end

app/models/join.rb
class Join < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  has_many :groups
  has_many :joins, dependent: :destroy
  has_many :join_groups,through: :joins,source: :group
  has_many :boards, dependent: :destroy
  has_many :board_groups,through: :joins,source: :group
  validates :name, presence: true, length: { maximum: 10 }
  validates :email, presence: true,uniqueness: true,length: { maximum: 255},format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, on: :create, length: { minimum: 6 }
  validates :sex, length: { maximum: 10 }
  validates :age, length: { maximum: 10 }
  validates :introduction, length: { maximum: 40 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :login_check

  def show
    @group = Group.find_by(id: params[:id])
    @join = current_user.joins.find_by(group_id: @group.id)
    @boards = @group.boards.order('created_at DESC')
    @board = Board.new
    @board.group_id = @group.id
    @board.user_id = current_user.id
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to board_path(@board.group_id),notice:"投稿しました！"
    else
      redirect_to board_path(@board.group_id),notice:"1~140字で内容を書き込んでください！"
    end
  end

  def update
    @board = Board.find(params[:id])
    @board.remove_image!
    if @board.user == current_user || @board.group.user_id == current_user.id
      @board.update(content:"書き込みは削除されました。", image: "nil")
      redirect_to board_path(@board.group_id),notice:"投稿内容を削除しました！"
    else
      redirect_to board_path(@board.group_id),notice:"書き込みの削除は投稿者かサークル代表者しかできません"
    end
  end

private
  def board_params
    params.require(:board).permit(:group_id,:user_id,:content,:image,:remove_iamge)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :login_check,only:[:show,:new,:confirm,:create,:edit,:update,:destroy]
  before_action :set_group,only:[:show,:edit,:manager_edit,:update,:destroy]
  before_action :other_than_manager_edit_block,only:[:edit,:manager_edit,:destroy]

  def home
    index
  end

  def index
    @groups = Group.all.order('updated_at DESC')
  end

  def show
    @join = current_user.joins.find_by(group_id: @group.id)
    @manager_user = @group.user
    @member_user = @group.join_users
  end

  def new
    if params[:back]
      @group = Group.new(group_params)
    else
      @group = Group.new
    end
  end

  def confirm
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    render :new if @group.invalid?
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      Join.create(user_id: current_user.id , group_id: @group.id)
      redirect_to groups_path,notice:"サークルを作成しました。"
    else
      render new_group_path
    end
  end

  def edit
  end

  def manager_edit
    @member_user = @group.join_users
    @manager_user = @group.user
  end

  def update
    if @group.update(group_params)
      redirect_to group_path(params[:id]),notice:"サークル情報を変更しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path,notice:"グループを削除しました。"
  end

private
  def group_params
    params.require(:group).permit(:name,:user_id,:place,:time,:content,group_attributes: [:user_id,:group_id])
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def other_than_manager_edit_block
    unless current_user == User.find_by(id: @group.user_id)
      redirect_to group_path(params[:id]),notice:"サークル情報の編集は代表者のみ可能です。"
    end
  end

end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController
  before_action :login_check
  
  def create
    join = current_user.joins.create(group_id: params[:group_id])
    @group = join.group
    @manager_user = @group.user
    @member_user = current_user
    JoinMailer.join_mail(@group,@manager_user,@member_user).deliver
    redirect_to board_path(params[:group_id]), notice: "サークルに参加しました!掲示板で報告しましょう！"
  end

  def destroy
    join = current_user.joins.find_by(group_id: params[:id]).destroy
    redirect_to groups_path, notice: "退会しました。"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:notice] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,only:[:show,:edit,:pass_edit,:update,:destroy_confirm,:destroy]
  before_action :correct_user,only:[:edit,:pass_edit,:destroy_confirm]

  def show
    @join_groups = @user.join_groups
  end

  def new
    if params[:back]
      @user = User.new(user_params)
    else
      @user = User.new
    end
  end

  def confirm
    @user = User.new(user_params)
    render :new if @user.invalid?
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id),notice:"アカウントを作成しました！"
    else
      render new_user_path
    end
  end

  def edit
  end

  def pass_edit
  end

  def update
      if @user.update(user_params)
        redirect_to user_path(params[:id]),notice:"情報を変更しました！"
      else
        if params[:pass_edit]
          render 'pass_edit'
        else
          render 'edit'
        end
      end
  end

  def  destroy_confirm
      redirect_to user_path(params[:id]),notice:"自分が代表のサークルがある場合、アカウントは削除できません。" if @user.groups.present?
  end

  def destroy
    @user.destroy
    redirect_to root_path,notice:"ユーザー情報を削除しました。ご利用ありがとうございました。"
  end

private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:sex,:age,:introduction)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def correct_user
    unless current_user.id == @user.id
      redirect_to user_path(params[:id]),notice:"他人のユーザー情報は変更できません。"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def simple_time(time)
    time.strftime("%Y-%m-%d　%H:%M　")
  end
  def  page_title
    title = "シュミティア -趣味の幅をゆるーく広げるサイト- "
    title = @page_title + " | " + title if @page_title
    title
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_groups_path
    elsif action_name == 'edit'
      group_path
    end
  end
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id:session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def login_check
    if logged_in?
    else
      redirect_to new_session_path,notice:"シュミティアを使うにはログインしてください"
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/show.html.erb
<h1 class="page_title"><%= @group.name %>の掲示板</h1>

<div class="submit_box">
  <p class="submit_box_info">サークルの活動記録や連絡事項等を書き込みましょう!</p>

  <%= form_with( model:@board ,local:true ,url:boards_path ,method:'post' )do |f| %>
    <%= f.hidden_field :group_id %>
    <%= f.hidden_field :user_id %>
    <p><%= f.label :image %></p>
    <p><%= f.file_field :image %></p>
    <p><%= f.label :書き込み内容 %></p>
    <p><%= f.text_area :content , :cols => 83, :rows => 10 %></p>
    <p><%= f.submit :送信 ,data: { confirm: '書き込んでよろしいですか？' }%></p>
  <% end %>
</div>

<h2 class="link_btn board_show_link_btn"><%= link_to 'サークルHOMEへ',group_path(@group.id) %></h2>

<% if @group.user_id == current_user.id %>
<% else %>
  <% if @join.present? %>
    <p class="link_btn board_show_join_btn"><%= link_to 'サークルから退会する', join_path(id: @group.id),data: { confirm: 'サークルから退会します、よろしいですか？' }, method: :delete %><p>
  <% else %>
    <p class="link_btn board_show_join_btn"><%= link_to 'サークルに　　　参加する', joins_path(group_id: @group.id),data: { confirm: 'サークルに参加すると代表にメールアドレスが公開されます。よろしいですか？' }, method: :post %></p>
  <% end %>
<% end %>


  <% @boards.each do |board| %>
    <div class="boards_box">
      <d class="boards_info">
        投稿者：<%= "☆" if @group.join_users.include?(board.user) %><%= board.user.name %>
      </d>
      <d class="boards_info">投稿日時：<%= simple_time(board[:created_at] ) %></d>
      <% if board.user == current_user  || board.group.user_id == current_user.id %>
        <%if board.content != "書き込みは削除されました。" %>
          <d><%= link_to '削除' ,board_path(board.id), method: :patch,data: { confirm: '書き込みを削除しますか？※枠は消えません。' } %></d>
        <% end %>
      <% end %>
      <p class=""><%= image_tag board.image unless board.image == nil %></p>
      <p class=""><%= board.content %></p>

    </div>
  <% end %>


  <div class="boards_box">
      <d class="boards_info">投稿者：------</d>
      <d class="boards_info">投稿日時：<%= simple_time(@group[:created_at] ) %></d>
      <p>サークルの活動記録や、質問等を書き込みましょう！</p>
  </div>

app/views/groups/_form.html.erb
<div class="notice">
  <% if @group.errors.any? %>
    <% @group.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>
</div>


<div class="form_box">
  <%= form_with( model:@group ,local:true ,url: choose_new_or_edit )do |f| %>
    <h4><%= f.label :サークル名： %><%= f.text_field :name %></h4>
    <d class="date_time_field"><%= f.label :活動場所： %><%= f.text_field :place %></d>
    <d class="date_time_field"><%= f.label :活動日時 %><%= f.text_field :time %></d>

    <div class="form_content_field">
      <p><%= f.label :概要 %></p>
      <p><%= f.text_area :content , :cols => 90, :rows => 11.5 %></p>
    </div>
    <p class="form_submit"><%= f.submit :送信 %></p>
  <% end %>
</div>

app/views/groups/_groups.html.erb
<div class="index_area">
  <% @groups.each do |group| %>
    <div class="index_box">
      <h4><%= group.name %></h4>

      <d class="index_info">活動場所：<%= group.place %></d>
      <d class="index_info">活動時間：<%= group.time %></d>
      <d class="index_info">メンバー：<%= group.join_users.count %>人</d>
      <d class="index_info">最終更新：<%= simple_time( group.updated_at ) %></d>
      <div class="index_link_area">
        <p class="link_btn"><%= link_to 'サークルHOME',group_path(group.id) %></p>
        <p class="link_btn"><%= link_to '掲示板',board_path(group.id) %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/confirm.html.erb
<% @page_title = "サークルをつくる" %>
<h1 class="page_title">以下の内容で作成してよろしいでしょうか？</h1>

<div class="form_box">
  <h4>サークル名：<%= @group.name %></h4>
  <label class="date_time_field">活動場所：<%= @group.place %></label>
  <label class="date_time_field">活動時間：<%= @group.time %></label>
  <p class="form_content_field"><%= @group.content %></p>

  <%= form_with( model:@group ,local:true ,url:new_group_path ,method:'get' ) do |f| %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :place %>
    <%= f.hidden_field :time %>
    <%= f.hidden_field :content %>
    <p class="form_submit">
      <%= f.submit :戻る ,name:'back' %>
    </p>
  <% end %>
  <%= form_with( model:@group ,local:true ) do |f| %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :place %>
    <%= f.hidden_field :time %>
    <%= f.hidden_field :content %>
    <p class="form_submit">
      <%= f.submit :作成する %>
    </p>
  <% end %>

</div>

app/views/groups/edit.html.erb
<% @page_title = "サークル情報を変更する" %>
<h1 class="page_title">サークル情報を変更する</h1>

<%= render 'form' %>

app/views/groups/home.html.erb
<div class="home_title_box">
  <img src="/images/home5.jpg" class="home_back_img">
  <div class="home_title">
    <img src="/images/pawsbig.png" class="home_title_img">
    <i>Syumitier</i>
    <p>-趣味の幅をゆるーく広げるサイト-</p>
  </div>
</div>


<div class="home_info">
  <h2>【Syumitierは新たな趣味を探す人のためのコミュニティサイトです。】</h2>
  <p>・サークルを作成してメンバーを募ったり、サークルに参加したりできます。</p>
  <p>・サークル活動の記録や質問、連絡等のできる掲示板機能があります。</p>
  <p>・まずはアカウント作成して気になる趣味をさがしてみよう！</p>
  <a><%= link_to "新規登録", new_user_path, class:"link_btn" %></a>

</div>

<%= render 'groups' %>

app/views/groups/index.html.erb
<% @page_title = "サークルをさがす" %>

<h1 class="page_title">サークル一覧</h1>

<%= render 'groups' %>

app/views/groups/manager_edit.html.erb
<% @page_title = "管理者をうつす" %>
<h1 class="page_title">管理者をうつす</h1>

<% if @group.errors.any? %>
  <% @group.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
<% end %>


<%= form_with( model:@group ,local:true )do |f| %>
  <div class="show_member_box">
    <p>受け渡したいメンバーを選択してください。</p>
    <% @member_user.each_with_index do |user,i| %>
      <% unless user == @manager_user %>
        <%= user.name  %>
        <% if i == 0 %>
          <%= f.radio_button :user_id,user.id, checked:"checked" if i == 0 %>
        <% else %>
          <%= f.radio_button :user_id,user.id %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <p class="manager_edit_btn"><%= f.submit :送信,data: { confirm: '権限を受け渡すと元には戻せません。よろしいですか？' } %></p>
<% end %>

app/views/groups/new.html.erb
<% @page_title = "サークルをつくる" %>
<h1 class="page_title">サークルをつくる</h1>

<%= render 'form' %>

app/views/groups/show.html.erb
<% @page_title = "#{@group.name}" %>
<h1 class="page_title"><%= @group.name %>のページ</h1>

<div class="group_show_box">
  <d>代表：<%= link_to @manager_user.name, user_path(@manager_user.id) %></d>
  <d>活動場所：<%= @group.place %></d>
  <d>活動時間：<%= @group.time %></d>
  <d>メンバー：<%= @member_user.count %>人</d>
  <d>代表者連絡先：
    <% if @join.present? %>
      <%= @manager_user.email %>
    <% else %>
      サークルメンバーのみ表示されます
    <% end %>
  </d>
  <div class=show_content_box>
    <p class=show_content_field><%= @group.content %></p>
  </div>


  <div class="show_btn_box">
    <% if @group.user_id == current_user.id %>
      <p class="link_btn">
        <%= link_to 'サークル情報編集',edit_group_path(id: @group.id),
        data: { confirm: '本当に編集してよろしいですか？' } %>
      </p>
      <p class="link_btn">
        <%= link_to 'サークルを　　　削除する',group_path(id: @group.id), method: :delete,
        data: { confirm: '本当に編集してよろしいですか？' } %>
      </p>
      <%if @member_user.count > 1 %>
        <p class="link_btn">
          <%= link_to '代表者を変える',manager_edit_groups_path(id: @group.id),
          data: { confirm: '権限受け渡し画面に移行してよろしいですか？' } %>
        </p>
      <% end %>
    <% else %>
      <% if @join.present? %>
        <p class="link_btn">
          <%= link_to 'サークルから退会',join_path(id: @group.id),method: :delete,
          data: { confirm: 'サークルから退会します、よろしいですか？' } %>
        </p>
      <% else %>
        <p class="link_btn">
          <%= link_to 'サークルに　　　参加する', joins_path(group_id: @group.id),method: :post,
          data:{ confirm: 'サークルに参加すると代表にメールアドレスが公開されます。よろしいですか？' }%>
        </p>
      <% end %>
    <% end %>
    <p class="link_btn"><%= link_to '掲示板へ',board_path(@group.id) %></p>
  </div>

  <div class="show_member_box">
    <p>参加者一覧</p>
    <p>代表：<%= link_to @manager_user.name, user_path(@manager_user.id) %></p>
    <% @member_user.each do |user| %>
      <% unless user == @manager_user %>
        <a class="show_member_box_in"><%= link_to user.name, user_path(user.id) %></a>
      <% end %>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrap">
      <header class="header_area">
        <div class="site_title">
          <img src="/images/paws.png">
          <i>Syumitier</i>
          <p>-趣味の幅をゆるーく広げるサイト-</p>
        </div>
        <div class="login_area">
          <% if logged_in? %>
            <a><%= link_to "MyPage", user_path(current_user.id), class:"header_btn" %></a>
            <a><%= link_to "ログアウト", session_path(current_user.id), method: :delete, class:"header_btn" %></a>
          <% else %>
            <a><%= link_to "新規登録", new_user_path, class:"header_btn" %></a>
            <a><%= link_to "ログイン", new_session_path, class:"header_btn" %></a>
          <% end %>
        </div>
      </header>

      <div class="info_alea">
          <%= link_to "HOME",root_path ,class:"info_btn"%>
          <%= link_to "サークルを『さがす』",groups_path,class:"info_btn" %>
          <%= link_to "サークルを『つくる』",new_group_path,class:"info_btn" %>
      </div>

      <p class="notice"><%= notice %></p>

      <%= yield %>

    </div>
    <footer  class="fotter_area">
      <p>tbt's exercises application</p>
    </footer>
  </body>
</html>

app/views/users/confirm.html.erb
<% @page_title = "ユーザー新規登録" %>
<h1 class="page_title">以下の内容で作成してよろしいでしょうか？</h1>


<div class="user_new_box">
  <div class="site_title site_title_user_new">
    <img src="/images/paws.png">
    <i>Syumitier</i>
    <p>-趣味の幅をゆるーく広げるサイト-</p>
  </div>

  <div>
    <div>
      <p>名前：<%= @user.name %></p>
      <p>email：<%= @user.email %></p>
      <p>password：<%= "●" * @user.password.split(//).size %></p>
      <p>性別：<%= @user.sex %></p>
      <p>年齢：<%= @user.age %></p>
      <p>ひとこと</p>
      <p class="user_confirm_introduction"><%= @user.introduction %></p>
    </div>

  </div>
  <div class="user_new_btn">
    <%= form_with( model:@user ,local:true ) do |f| %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :password %>
      <%= f.hidden_field :password_confirmation %>
      <%= f.hidden_field :sex %>
      <%= f.hidden_field :age %>
      <%= f.hidden_field :introduction %>
      <p><%= f.submit :作成する %></p>
    <% end %>

    <%= form_with( model:@user ,local:true ,url:new_user_path ,method:'get' ) do |f| %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :sex %>
      <%= f.hidden_field :age %>
      <%= f.hidden_field :introduction %>
      <p><%= f.submit :戻る ,name:'back' %></p>
    <% end %>
  </div>
</div>

app/views/users/destroy_confirm.html.erb
<% @page_title = "本当にアカウントを削除しますか？" %>
<h1 class="page_title">本当にアカウントを削除しますか？</h1>

<div class="user_destroy_box">
  <h2>アカウントを削除すると元には戻せません。</h2>
  <p class="link_btn user_destroy_btn"><%= link_to 'アカウント削除', user_path(id: @user.id), method: :delete,data: { confirm: 'アカウントを削除します、よろしいですか？' } %></p>
  <p class="link_btn user_destroy_btn"><%= link_to 'もどる', user_path(id: @user.id) %></p>
</div>

app/views/users/edit.html.erb
<% @page_title = "ユーザー情報を編集する" %>
<h1 class="page_title">ユーザー情報を編集する</h1>

<div class="notice">
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>
</div>

<div class="user_edit_box">
  <%= form_with( model:@user ,local:true )do |f| %>
    <p><%= f.label :ユーザー名 %></p>
    <p><%= f.text_field :name %></p>
    <p><%= f.label :性別 %></p>
    <p><%= f.text_field :sex %></p>
    <p><%= f.label :年齢 %></p>
    <p><%= f.text_field :age %></p>
    <p><%= f.label :自己紹介 %></p>
    <p><%= f.text_area :introduction, :cols => 19, :rows => 4 %></p>

    <p><%= f.submit :変更する %></p>
  <% end %>
</div>

app/views/users/new.html.erb
<% @page_title = "ユーザー新規登録" %>
<h1 class="page_title">ユーザー新規登録</h1>

<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
<% end %>

<div class="user_new_box">
  <div class="site_title site_title_user_new">
    <img src="/images/paws.png">
    <i>Syumitier</i>
    <p>-趣味の幅をゆるーく広げるサイト-</p>
  </div>

  <%= form_with( model:@user ,local:true ,url: confirm_users_path )do |f| %>
    <div class="user_new_form_left">
      <p><%= f.label :ユーザー名※ %></p>
      <p><%= f.text_field :name %></p>
      <p><%= f.label :mail※ %></p>
      <p><%= f.text_field :email %></p>
      <p><%= f.label :password※ %></p>
      <p><%= f.password_field :password %></p>
      <p><%= f.label :"password(確認)※" %></p>
      <p><%= f.password_field :password_confirmation %></p>
    </div>
    <div class="user_new_form_right">
      <p><%= f.label :性別 %></p>
      <p><%= f.text_field :sex %></p>
      <p><%= f.label :年齢 %></p>
      <p><%= f.text_field :age %></p>
      <p><%= f.label :ひとこと %></p>
      <p><%= f.text_area :introduction, :cols => 19, :rows => 4 %></p>
    </div>
    <div class="user_new_btn">
      <p>※は必ず入力してください</p>
      <p><%= f.submit :確認画面へ %></p>
    </div>
  <% end %>
</div>

app/views/users/pass_edit.html.erb
<% @page_title = "ユーザー情報を編集する" %>
<h1 class="page_title">メールとパスワードの変更</h1>

<div class="notice">
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>
</div>

<div class="user_edit_box">
  <%= form_with( model:@user ,local:true )do |f| %>
    <p><%= f.label :mail %></p>
    <p><%= f.text_field :email %></p>
    <p><%= f.label :新しいpassword %></p>
    <p><%= f.password_field :password %></p>
    <p><%= f.label :"新しいpassword(確認)" %></p>
    <p><%= f.password_field :password_confirmation %></p>

    <p><%= f.submit :変更する ,name:'pass_edit' %></p>
  <% end %>
</div>

app/views/users/show.html.erb
<h1 class="page_title"><%= @user.name %>さんのページ</h1>

<div class="user_show_box">
  <d>名前：<%= @user.name %></d>
  <d>性別：<%= @user.sex %></d>
  <d>年齢：<%= @user.age %></d>
    <% if @join_groups.find_by(user_id: current_user.id ) && @user.id != current_user.id %>
      <d>email：<%= @user.email %></d>
    <% end %>

  <% if @user.id == current_user.id %>
    <d>email：<%= @user.email %></d>
    <div>
      <p class="link_btn user_show_btn"><%= link_to 'アカウント削除', destroy_confirm_users_path(id: @user.id),data: { confirm: '本当に削除してよろしいですか？自分が代表のサークルがあると削除できません' } %></p>
      <p class="link_btn user_show_btn"><%= link_to 'プロフィール編集', edit_user_path(id: @user.id),data: { confirm: '本当に編集してよろしいですか？' } %></p>
      <p class="link_btn user_show_btn"><%= link_to 'メールと　　　　パスワードの編集',pass_edit_users_path(id: @user.id),data: { confirm: '本当に編集してよろしいですか？' } %></p>
    </div>
  <% end %>

  <div class="introduction_box">
    <p>ひとこと：</p>
    <p><%= @user.introduction %></p>
  </div>

  <div class="show_group_box">
    <p>参加しているサークル（代表しているサークルは☆）</p>
    <% @join_groups.each do |group| %>
      <span class="show_group_box_in">
        <%= "☆" if group.user_id == @user.id %>
        <%= link_to group.name, group_path(group.id) %>
        <%= link_to "掲示板", board_path(group.id) %>
      </span>
    <% end %>
  </div>
</div>